# buildkite.yml

steps:
  - name: "Build image"
    command: "docker build -t sysdig-agent ."
    agents:
      - "plain_utils=true"

  - wait

  - name: "Tag image as staging"
    command: "docker tag sysdig-agent quay.io/everydayhero/sysdig-agent:staging"
    branches: master
    agents:
      - "plain_utils=true"

  - wait

  - name: "Push staging build"
    command: "docker push quay.io/everydayhero/sysdig-agent:staging"
    branches: master
    agents:
      - "plain_utils=true"

  - wait

  - name: "Deploy to staging admin"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  - wait

  - name: "Smoke test"
    command: "plain-utils ansible $ENVIRONMENT master coreos -l admin -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  - wait

  - name: "Deploy to staging"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l \\!kibana,\\!consul-server,\\!rabbitmq,\\!admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  - wait

  - name: "Smoke Test"
    command: "sleep 30; plain-utils ansible $ENVIRONMENT master coreos -l \\!rabbitmq,\\!consul-server -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  - block

  - name: "Tag image as production"
    command: "docker tag sysdig-agent quay.io/everydayhero/sysdig-agent:production"
    branches: master
    agents:
      - "plain_utils=true"

  - wait

  - name: "Push production build"
    command: "docker push quay.io/everydayhero/sysdig-agent:production"
    branches: master
    agents:
      - "plain_utils=true"

  - wait

  - name: "Deploy to production admin"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

  - wait

  - name: "Smoke Test"
    command: "plain-utils ansible $ENVIRONMENT master coreos -l admin -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

  - wait

  - name: "Deploy to production"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l \\!kibana,\\!consul-server,\\!rabbitmq,\\!admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

  - wait

  - name: "Smoke Test"
    command: "sleep 30; plain-utils ansible $ENVIRONMENT master coreos -l \\!rabbitmq,\\!consul-server -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

