# buildkite.yml

steps:
  -
    name: "Build Docker image (staging)"
    command: "docker build -t 'quay.io/everydayhero/sysdig-agent:staging' ."
    branches: master
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Push new build"
    command: "docker push quay.io/everydayhero/sysdig-agent:staging"
    branches: master
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Deploy to admin"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  -
    type: "waiter"

  -
    name: "Smoke test"
    command: "plain-utils ansible $ENVIRONMENT master coreos -l admin -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  -
    type: "waiter"

  -
    name: "Deploy to staging"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l \\!kibana,\\!consul-server,\\!rabbitmq,\\!admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  -
    type: "waiter"

  -
    name: "Smoke Test"
    command: "sleep 30; plain-utils ansible $ENVIRONMENT master coreos -l \\!rabbitmq,\\!consul-server -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "staging"

  -
    type: "waiter"

  -
    name: "Build Docker image (production)"
    command: "docker build -t 'quay.io/everydayhero/sysdig-agent:production' ."
    branches: master
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Push new build"
    command: "docker push quay.io/everydayhero/sysdig-agent:production"
    branches: master
    agents:
      - "plain_utils=true"

  -
    type: "waiter"

  -
    name: "Deploy to admin"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

  -
    type: "waiter"

  -
    name: "Smoke Test"
    command: "plain-utils ansible $ENVIRONMENT master coreos -l admin -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

  -
    type: "waiter"

  -
    name: "Deploy to production"
    command: "plain-utils ansible-playbook $ENVIRONMENT master -l \\!kibana,\\!consul-server,\\!rabbitmq,\\!admin --tags sysdig coreos.yml"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"

  -
    type: "waiter"

  -
    name: "Smoke Test"
    command: "sleep 30; plain-utils ansible $ENVIRONMENT master coreos -l \\!rabbitmq,\\!consul-server -m raw -a \"'docker ps | grep sysdig-agent'\";"
    branches: master
    agents:
      - "plain_utils=true"
    env:
      ENVIRONMENT: "production"
